server:
  port: 8080

spring:
  application:
    name: deltastore
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

# Legacy configuration (kept for backward compatibility)
app:
  storage:
    bucket-name: ${STORAGE_BUCKET_NAME:deltastore-dev}
    endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
    access-key: ${STORAGE_ACCESS_KEY:minioadmin}
    secret-key: ${STORAGE_SECRET_KEY:minioadmin}

# New centralized configuration
deltastore:
  performance:
    cache-ttl-ms: 30000          # 30 seconds cache TTL
    batch-timeout-ms: 50         # 50ms batch processing
    max-batch-size: 100          # Max records per batch
    max-retries: 3               # Retry attempts for failed operations
    connection-pool-size: 200    # S3 connection pool size
    write-timeout-ms: 30000      # Write operation timeout
    commit-threads: 2            # Number of commit executor threads
    
  schema:
    evolution-policy: BACKWARD_COMPATIBLE
    enable-schema-validation: true
    auto-register-schemas: true
    cache-schemas: true
    schema-cache-ttl-ms: 300000  # 5 minutes schema cache
    
  storage:
    type: S3A
    base-path: "/delta-tables"
    partition-strategy: DATE_BASED
    enable-compression: true
    compression-codec: "snappy"
    
  # No tables configured in base profile
  # All entity configurations are profile-specific
  # Production deployments should define their own entity configurations
  tables: {}

logging:
  level:
    com.example.deltastore: ${LOG_LEVEL:INFO}
    org.apache.hadoop: WARN
    io.delta: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
