spring:
  config:
    activate:
      on-profile: local

app:
  storage:
    bucket-name: "my-bucket"
    endpoint: "http://localhost:9000"
    access-key: "minio"
    secret-key: "minio123"

logging:
  level:
    com.example.deltastore: DEBUG
    org.springframework.web: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
